version: '2'

x-defaults: &defaults
  cap_add:
   - NET_ADMIN
  image: kylemanna/openvpn
  restart: always
  volumes:
   - ./conf:/etc/openvpn
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv6.conf.default.forwarding=1
    - net.ipv6.conf.all.forwarding=1

services:
  openvpn-udp:
    <<: *defaults
    container_name: openvpn-udp
    command: "ovpn_run"
    ports:
     - "1194:1194/udp"

  openvpn-tcp:
    <<: *defaults
    container_name: openvpn-tcp
    command: "ovpn_run --proto tcp"
    ports:
     - "1194:1194/tcp"


